[package]
name = "com-core"
version = "0.1.0"

readme = "readme.md"

[dependencies]
winapi = "0.2"
ole32-sys = "0.2"
bitflags = "0.7"
hresult = { path = "../com-types/hresult", version = "0.1" }
com-sys = { path = "../com-sys", version = "0.1" }
